"""remove column from location

Revision ID: 8565613ab259
Revises: 4f99a28814f8
Create Date: 2025-11-08 23:36:57.976723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8565613ab259'
down_revision: Union[str, Sequence[str], None] = '4f99a28814f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_column('locations', 'name', schema='weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'locations',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        schema='weather',
    )
    op.create_table(
        'alembic_version',
        sa.Column(
            'version_num',
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            'version_num', name=op.f('alembic_version_pkc')
        ),
    )
    # ### end Alembic commands ###
