"""create weather schema

Revision ID: 75f3afe88a30
Revises: 
Create Date: 2025-11-06 19:00:11.046788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f3afe88a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS weather;")
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openweather_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openweather_id'),
    schema='weather'
    )
    op.create_table('weather_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_avg', sa.Float(), nullable=True),
    sa.Column('humidity_avg', sa.Float(), nullable=True),
    sa.Column('precipitation_sum', sa.Float(), nullable=True),
    sa.Column('wind_speed_avg', sa.Float(), nullable=True),
    sa.Column('readings_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['weather.locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='weather'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_aggregates', schema='weather')
    op.drop_table('locations', schema='weather')
    # ### end Alembic commands ###
