"""create weather aggregates location id date unique constraint

Revision ID: 8d7888dd2faf
Revises: 75f3afe88a30
Create Date: 2025-11-06 19:07:23.063387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7888dd2faf'
down_revision: Union[str, Sequence[str], None] = '75f3afe88a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
